name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1      
      - name: install  
      - uses: bahmutov/npm-install@v1
      - run: yarn
      - name: Build
      - uses: bahmutov/npm-install@v1
      - run: yarn build
    
